title:Jeson S Saldanha 
logo: "/profile.jpg?raw=true"
description:>
  <br><br>
  <a href="mailto:shwnsaldanha@gmail.com">shwnsaldanha@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/i-am-shawn/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal

