title: Jeson S Saldanha # your name (or website title) here
logo: "/profileCircleNew.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
   <a href="mailto:shwnsaldanha@gmail.com">shwnsaldanha@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/i-am-shawn">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal

