title: Jeson Shawn Saldanha 
logo: "/profile.jpg?raw=true"
description: > 
 Software Engineer
  <br><br>
  <a href="mailto:shwnsaldanha@gmail.com">shwnsaldanha@gmail.com</a>
  <br>
  <a href="www.linkedin.com/in/i-am-shawn/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
